apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Base64 encoded passwords
  # orderpass -> b3JkZXJwYXNz
  POSTGRES_ORDER_PASSWORD: b3JkZXJwYXNz
  # paymentpass -> cGF5bWVudHBhc3M=
  POSTGRES_PAYMENT_PASSWORD: cGF5bWVudHBhc3M=
  # inventorypass -> aW52ZW50b3J5cGFzcw==
  POSTGRES_INVENTORY_PASSWORD: aW52ZW50b3J5cGFzcw==
  # notificationpass -> bm90aWZpY2F0aW9ucGFzcw==
  POSTGRES_NOTIFICATION_PASSWORD: bm90aWZpY2F0aW9ucGFzcw==
  # sagapass -> c2FnYXBhc3M=
  POSTGRES_SAGA_PASSWORD: c2FnYXBhc3M=
  # fulfillmentpass -> ZnVsZmlsbG1lbnRwYXNz
  POSTGRES_FULFILLMENT_PASSWORD: ZnVsZmlsbG1lbnRwYXNz
  # rootpass -> cm9vdHBhc3M=
  POSTGRES_ROOT_PASSWORD: cm9vdHBhc3M=
