apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_ORDER_PASSWORD: b3JkZXJwYXNz
  POSTGRES_PAYMENT_PASSWORD: cGF5bWVudHBhc3M=
  POSTGRES_INVENTORY_PASSWORD: aW52ZW50b3J5cGFzcw==
  POSTGRES_NOTIFICATION_PASSWORD: bm90aWZpY2F0aW9ucGFzcw==
  POSTGRES_SAGA_PASSWORD: c2FnYXBhc3M=
  POSTGRES_FULFILLMENT_PASSWORD: ZnVsZmlsbG1lbnRwYXNz
  POSTGRES_ROOT_PASSWORD: cm9vdHBhc3M=
