global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
    relabel_configs:
      - target_label: service
        replacement: order-service

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
    relabel_configs:
      - target_label: service
        replacement: payment-service

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
    relabel_configs:
      - target_label: service
        replacement: notification-service

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8084']
    relabel_configs:
      - target_label: service
        replacement: inventory-service

  - job_name: 'saga-orchestrator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
    relabel_configs:
      - target_label: service
        replacement: saga-orchestrator

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    relabel_configs:
      - target_label: service
        replacement: gateway-service
